# Platform hardening
sudo yum install kernel-modules-extra
sudo sysctl -w net.ipv4.conf.all.accept_redirects=0
sudo sysctl -w net.ipv4.conf.all.send_redirects=0
sudo sysctl -w kernel.modules_disabled=1
sudo systemctl stop rpcbind.service
sudo systemctl disable rpcbind.service
sudo systemctl stop nfs-server.service
sudo systemctl disable nfs-server.service
sudo systemctl stop rpcbind.socket
sudo systemctl disable rpcbind.socket
sudo systemctl stop nfs-lock.service
sudo systemctl disable nfs-lock.service
sudo systemctl stop nfs-idmap.service
sudo systemctl disable nfs-idmap.service
sudo systemctl stop rpc-statd.service
sudo systemctl disable rpc-statd.service
sudo systemctl stop rpc-statd-notify.service
sudo systemctl disable rpc-statd-notify.service
sudo systemctl stop rpcbind.target
sudo systemctl disable rpcbind.target
sudo systemctl stop rpcbind.socket
sudo systemctl disable rpcbind.socket
sudo systemctl stop rpcbind.service
sudo systemctl disable rpcbind.service
sudo systemctl stop rpc-gssd.service
sudo systemctl disable rpc-gssd.service
sudo systemctl stop rpc-svcgssd.service
sudo systemctl disable rpc-svcgssd.service
sudo systemctl stop rpcbind.socket
sudo systemctl disable rpcbind.socket
sudo systemctl stop rpcbind.service
sudo systemctl disable rpcbind.service
sudo systemctl stop rpcbind.target
sudo systemctl disable rpcbind.target
sudo systemctl stop rpcbind.socket
sudo systemctl disable rpcbind.socket
sudo systemctl stop rpcbind.service
sudo systemctl disable rpcbind.service
sudo systemctl stop rpc-gssd.socket
sudo systemctl disable rpc-gssd.socket
sudo systemctl stop rpc-svcgssd.socket
sudo systemctl disable rpc-svcgssd.socket
sudo systemctl stop rpcbind.socket
sudo systemctl disable rpcbind.socket
sudo systemctl stop rpcbind.service
sudo systemctl disable rpcbind.service
sudo systemctl stop rpcbind.target
sudo systemctl disable rpcbind.target
sudo systemctl stop rpcbind.socket
sudo systemctl disable rpcbind.socket
sudo systemctl stop rpcbind.service
sudo systemctl disable rpcbind.service
sudo systemctl stop rpc-gssd.service
sudo systemctl disable rpc-gssd.service
sudo systemctl stop rpc-svcgssd.service
sudo systemctl disable rpc-svcgssd.service
sudo systemctl stop rpcbind.socket
sudo systemctl disable rpcbind.socket
sudo systemctl stop rpcbind.service
sudo systemctl disable rpcbind.service
sudo systemctl stop rpcbind.target
sudo systemctl disable rpcbind.target
sudo systemctl stop rpcbind.socket
sudo systemctl disable rpcbind.socket
sudo systemctl stop rpcbind.service
sudo systemctl disable rpcbind.service
sudo systemctl stop rpc-gssd.socket
sudo systemctl disable rpc-gssd.socket
sudo systemctl stop rpc-svcgssd.socket
sudo systemctl disable rpc-svcgssd.socket
sudo systemctl stop rpcbind.socket
sudo systemctl disable rpcbind.socket
sudo systemctl stop rpcbind.service
sudo systemctl disable rpcbind.service
sudo systemctl stop rpcbind.target
sudo systemctl disable rpcbind.target
sudo systemctl stop rpcbind.socket
sudo systemctl disable rpcbind.socket
sudo systemctl stop rpcbind.service
sudo systemctl disable rpcbind.service
sudo systemctl stop rpc-gssd.service
sudo systemctl disable rpc-gssd.service
sudo systemctl stop rpc-svcgssd.service
sudo systemctl disable rpc-svcgssd.service
sudo systemctl stop rpcbind.socket
sudo systemctl disable rpcbind.socket
sudo systemctl stop rpcbind.service
sudo systemctl disable rpcbind.service
sudo systemctl stop rpcbind.target
sudo systemctl disable rpcbind.target
sudo systemctl stop rpcbind.socket
sudo systemctl disable rpcbind.socket
sudo systemctl stop rpcbind.service
sudo systemctl disable rpcbind.service
sudo systemctl stop rpc-gssd.socket
sudo systemctl disable rpc-gssd.socket
sudo systemctl stop rpc-svcgssd.socket
sudo systemctl disable rpc-svcgssd.socket
sudo systemctl stop rpcbind.socket
sudo systemctl disable rpcbind.socket
sudo systemctl stop rpcbind.service
sudo systemctl disable rpcbind.service
sudo systemctl stop rpcbind.target
sudo systemctl disable rpcbind.target
sudo systemctl stop rpcbind.socket
sudo systemctl disable rpcbind.socket
sudo systemctl stop rpcbind.service
sudo systemctl disable rpcbind.service
sudo systemctl stop rpc-gssd.service
sudo systemctl disable rpc-gssd.service
sudo systemctl stop rpc-svcgssd.service
sudo systemctl disable rpc-svcgssd.service
sudo systemctl stop rpcbind.socket
sudo systemctl disable rpcbind.socket